### ISSUE TITLE
add VMC catalog in a ~20 arcmin radius around the HST field center

### ISSUE THREAD

**Issue by Johannes-Sahlmann** [spacetelescope/jwst-calibration-field#5]
The VMC catalog is now public: https://www.eso.org/sci/publications/announcements/sciann17232.html

The absolute and relative astrometric accuracy will have to be checked against Gaia DR2.

**Comment by tonysohn** [comment]
Leaving this answer here for the records. The latest (as of early 2021) VMC catalog released in Oct 2019 does not include the LMC calibration field - it only has the SMC + MC bridge/stream regions. I suggest closing this issue.
